create table DAILY_TEAM_STATS(
  id int not null AUTO_INCREMENT,
  team char(3) not null,
  opponent char(3) not null,
  homeAway char(1) not null,
  date date not null,
  PTS smallint,
  FG smallint,
  FGA smallint,
  FGpercent float(4,3),
  3P tinyint,
  3PA tinyint,
  3Ppercent float(4,3),
  FT tinyint,
  FTA tinyint,
  FTpercent float(4,3),
  ORB tinyint,
  DRB tinyint,
  TRB tinyint,
  AST tinyint,
  STL tinyint,
  BLK tinyint,
  TOV tinyint,
  PF tinyint,
  TSpercent float(4,3),
  eFGpercnet float(4,3),
  3PAr float(4,3),
  FTr float(4,3),
  ORBpercent float(3,1),
  DRBpercent float(3,1),
  TRBpercent float(3,1),
  ASTpercent float(3,1),
  STLpercent float(3,1),
  BLKpercent float(3,1),
  TOVpercent float(3,1),
  ORtg float(3,1),
  DRtg float(3,1),
  fanduel float(4,1),
  primary key(id)
)

